### ISSUE TITLE
Does not output html

### ISSUE THREAD

**Issue by ezawadzki** [oruelle/md_mermaid#1]
​Hi,

Thanks for this plugin.
I tried just to use your example in my shell. The intput :
```
~~~mermaid
graph TB
A --> B
B --> C
​~~~
```

still output the same, without `<div class="mermaid">`.

My environment :
**md-mermaid**: 0.1.0
**markdown**: 3.2.2
**Python**:  3.7.5

Best,

Emilie

**Comment by woile** [comment]
Same issue!

**Comment by oruelle** [comment]
Issue solved !
